version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./src:/home/node/src
      - ./pages:/home/node/pages
      - ./public:/home/node/public
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=80
    ports:
      - 80:80
  redis:
    image: redis